### ISSUE TITLE
Unhandled error event

### ISSUE THREAD

**Issue by WeeJeWel** [athombv/node-linux-device#16]
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Remote connection unexpectedly closed.
    at Object.keys.forEach (/Users/emile/Git/homey-client/node_modules/linux-device/remote/client.js:126:29)
    at Array.forEach (<anonymous>)
    at Socket.serv.on (/Users/emile/Git/homey-client/node_modules/linux-device/remote/client.js:125:25)
    at Socket.Emitter.emit (/Users/emile/Git/homey-client/node_modules/component-emitter/index.js:133:20)
    at Socket.emit (/Users/emile/Git/homey-client/node_modules/linux-device/node_modules/socket.io-client/lib/socket.js:136:10)
    at Socket.onclose (/Users/emile/Git/homey-client/node_modules/linux-device/node_modules/socket.io-client/lib/socket.js:209:8)
    at Manager.<anonymous> (/Users/emile/Git/homey-client/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/Users/emile/Git/homey-client/node_modules/component-emitter/index.js:133:20)
    at Manager.onclose (/Users/emile/Git/homey-client/node_modules/linux-device/node_modules/socket.io-client/lib/manager.js:502:8)
    at Socket.<anonymous> (/Users/emile/Git/homey-client/node_modules/component-bind/index.js:21:15)
```

**Comment by jeroenvollenbrock** [comment]
This is caused by the lack of an error event listener, but this issue lacks the required context to fix it.
